"""add is_generating to student course

Revision ID: 01d998c96ffc
Revises: 728d628a5b8a
Create Date: 2025-01-16 12:19:02.102011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d998c96ffc'
down_revision: Union[str, None] = '728d628a5b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_parent', sa.Column('is_course_generating', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_course_parent', 'is_course_generating')
    # ### end Alembic commands ###
