"""add submission models

Revision ID: 04523b2d8375
Revises: b963bc45f308
Create Date: 2025-01-24 14:43:02.706505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04523b2d8375'
down_revision: Union[str, None] = 'b963bc45f308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_module_quiz_question_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('correct_submission', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.Column('quiz_question_object_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['quiz_question_object_id'], ['course_module_quiz_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_module_quiz_question_submission')
    # ### end Alembic commands ###
