"""initial commit

Revision ID: 159d5a0f4429
Revises: 
Create Date: 2024-11-07 00:01:30.988589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159d5a0f4429'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_unique_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anon_users_user_unique_id'), 'anon_users', ['user_unique_id'], unique=True)
    op.create_table('playground_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anon_users.user_unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_codes')
    op.drop_index(op.f('ix_anon_users_user_unique_id'), table_name='anon_users')
    op.drop_table('anon_users')
    # ### end Alembic commands ###
