"""new model

Revision ID: 3aab366d0549
Revises: b1bd356f24fd
Create Date: 2024-12-22 13:01:47.085399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aab366d0549'
down_revision: Union[str, None] = 'b1bd356f24fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_playground_lecture_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('programming_language', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('lecture_question_object_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_question_object_id'], ['user_created_lecture_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_playground_lecture_code')
    # ### end Alembic commands ###
