"""reset initial

Revision ID: 4529fdc3674d
Revises: 
Create Date: 2024-12-11 12:00:44.695783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4529fdc3674d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_unique_id', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anon_user_user_unique_id'), 'anon_user', ['user_unique_id'], unique=True)
    op.create_table('initial_playground_question',
    sa.Column('starter_code', sa.String(), nullable=False),
    sa.Column('solution_code', sa.String(), nullable=False),
    sa.Column('solution_time_complexity', sa.String(), nullable=False),
    sa.Column('test_case_list', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('example_io_list', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_oauth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_zero_unique_sub_id', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_auth_zero_unique_sub_id'), 'user_oauth', ['auth_zero_unique_sub_id'], unique=True)
    op.create_index(op.f('ix_user_oauth_email'), 'user_oauth', ['email'], unique=True)
    op.create_index(op.f('ix_user_oauth_email_verified'), 'user_oauth', ['email_verified'], unique=False)
    op.create_index(op.f('ix_user_oauth_family_name'), 'user_oauth', ['family_name'], unique=False)
    op.create_index(op.f('ix_user_oauth_full_name'), 'user_oauth', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_oauth_given_name'), 'user_oauth', ['given_name'], unique=False)
    op.create_index(op.f('ix_user_oauth_profile_picture_url'), 'user_oauth', ['profile_picture_url'], unique=False)
    op.create_table('custom_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anon_user_id', sa.String(), nullable=True),
    sa.Column('oauth_user_id', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anon_user_id'], ['anon_user.user_unique_id'], ),
    sa.ForeignKeyConstraint(['oauth_user_id'], ['user_oauth.auth_zero_unique_sub_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_created_playground_question',
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('example_io_list', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playground_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('programming_language', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('question_object_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_object_id'], ['user_created_playground_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_code')
    op.drop_table('user_created_playground_question')
    op.drop_table('custom_user')
    op.drop_index(op.f('ix_user_oauth_profile_picture_url'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_given_name'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_full_name'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_family_name'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_email_verified'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_email'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_auth_zero_unique_sub_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_table('initial_playground_question')
    op.drop_index(op.f('ix_anon_user_user_unique_id'), table_name='anon_user')
    op.drop_table('anon_user')
    # ### end Alembic commands ###
