"""submission lecture model

Revision ID: 4bca7ad3cc32
Revises: 969869e6ecf5
Create Date: 2024-12-24 23:16:14.058887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bca7ad3cc32'
down_revision: Union[str, None] = '969869e6ecf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_code_submission_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('test_case_boolean_result', sa.Boolean(), nullable=True),
    sa.Column('program_output_list', sa.String(), nullable=False),
    sa.Column('ai_feedback_response_string', sa.String(), nullable=False),
    sa.Column('user_created_lecture_question_object_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_created_lecture_question_object_id'], ['user_created_lecture_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_code_submission_history')
    # ### end Alembic commands ###
