"""add module description

Revision ID: 52f27357aac5
Revises: ceffe0c15f69
Create Date: 2025-01-15 00:01:38.996992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f27357aac5'
down_revision: Union[str, None] = 'ceffe0c15f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_module', sa.Column('module_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_course_module', 'module_description')
    # ### end Alembic commands ###
