"""pg question update

Revision ID: 5b442f2da6e4
Revises: e73d31c01ecd
Create Date: 2024-12-10 06:18:51.578535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b442f2da6e4'
down_revision: Union[str, None] = 'e73d31c01ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playground_question', 'starter_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('playground_question', 'solution_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('playground_question', 'solution_time_complexity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('playground_question', 'test_case_list',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playground_question', 'test_case_list',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('playground_question', 'solution_time_complexity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('playground_question', 'solution_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('playground_question', 'starter_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
