"""update new course models

Revision ID: 728d628a5b8a
Revises: 52f27357aac5
Create Date: 2025-01-15 11:47:37.731629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '728d628a5b8a'
down_revision: Union[str, None] = '52f27357aac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_parent', sa.Column('prompt_to_generate_syllabus', sa.String(), nullable=True))
    op.add_column('student_course_parent', sa.Column('syllabus_list_string', sa.String(), nullable=True))
    op.add_column('student_course_parent', sa.Column('student_learned_profile_object_id', sa.UUID(), nullable=True))
    op.drop_constraint('student_course_parent_custom_user_id_fkey', 'student_course_parent', type_='foreignkey')
    op.create_foreign_key(None, 'student_course_parent', 'student_learned_profile', ['student_learned_profile_object_id'], ['id'])
    op.drop_column('student_course_parent', 'created_at')
    op.drop_column('student_course_parent', 'updated_at')
    op.drop_column('student_course_parent', 'custom_user_id')
    op.add_column('student_learned_profile', sa.Column('user_profile_summary_text', sa.String(), nullable=True))
    op.add_column('student_learned_profile', sa.Column('user_full_chat_history', sa.String(), nullable=True))
    op.add_column('student_learned_profile', sa.Column('prompt_to_generate_profile_dict', sa.String(), nullable=True))
    op.drop_column('student_learned_profile', 'user_summary_text')
    op.drop_column('student_learned_profile', 'user_syllabus_dict')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_learned_profile', sa.Column('user_syllabus_dict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student_learned_profile', sa.Column('user_summary_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student_learned_profile', 'prompt_to_generate_profile_dict')
    op.drop_column('student_learned_profile', 'user_full_chat_history')
    op.drop_column('student_learned_profile', 'user_profile_summary_text')
    op.add_column('student_course_parent', sa.Column('custom_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('student_course_parent', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('student_course_parent', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_course_parent', type_='foreignkey')
    op.create_foreign_key('student_course_parent_custom_user_id_fkey', 'student_course_parent', 'custom_user', ['custom_user_id'], ['id'])
    op.drop_column('student_course_parent', 'student_learned_profile_object_id')
    op.drop_column('student_course_parent', 'syllabus_list_string')
    op.drop_column('student_course_parent', 'prompt_to_generate_syllabus')
    # ### end Alembic commands ###
