"""lecture models change

Revision ID: 735ab9869813
Revises: 0488018406fa
Create Date: 2024-12-23 21:20:35.756647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735ab9869813'
down_revision: Union[str, None] = '0488018406fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_main', sa.Column('code_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_main', 'code_url')
    # ### end Alembic commands ###
