"""update database

Revision ID: 7ee77a4e1898
Revises: 0171e23ce20c
Create Date: 2024-11-13 22:16:16.228342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee77a4e1898'
down_revision: Union[str, None] = '0171e23ce20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_oauth_email_verified', table_name='user_oauth')
    op.create_index(op.f('ix_user_oauth_email_verified'), 'user_oauth', ['email_verified'], unique=False)
    op.drop_index('ix_user_oauth_family_name', table_name='user_oauth')
    op.create_index(op.f('ix_user_oauth_family_name'), 'user_oauth', ['family_name'], unique=False)
    op.drop_index('ix_user_oauth_full_name', table_name='user_oauth')
    op.create_index(op.f('ix_user_oauth_full_name'), 'user_oauth', ['full_name'], unique=False)
    op.drop_index('ix_user_oauth_given_name', table_name='user_oauth')
    op.create_index(op.f('ix_user_oauth_given_name'), 'user_oauth', ['given_name'], unique=False)
    op.drop_index('ix_user_oauth_profile_picture_url', table_name='user_oauth')
    op.create_index(op.f('ix_user_oauth_profile_picture_url'), 'user_oauth', ['profile_picture_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_profile_picture_url'), table_name='user_oauth')
    op.create_index('ix_user_oauth_profile_picture_url', 'user_oauth', ['profile_picture_url'], unique=True)
    op.drop_index(op.f('ix_user_oauth_given_name'), table_name='user_oauth')
    op.create_index('ix_user_oauth_given_name', 'user_oauth', ['given_name'], unique=True)
    op.drop_index(op.f('ix_user_oauth_full_name'), table_name='user_oauth')
    op.create_index('ix_user_oauth_full_name', 'user_oauth', ['full_name'], unique=True)
    op.drop_index(op.f('ix_user_oauth_family_name'), table_name='user_oauth')
    op.create_index('ix_user_oauth_family_name', 'user_oauth', ['family_name'], unique=True)
    op.drop_index(op.f('ix_user_oauth_email_verified'), table_name='user_oauth')
    op.create_index('ix_user_oauth_email_verified', 'user_oauth', ['email_verified'], unique=True)
    # ### end Alembic commands ###
