"""new model

Revision ID: 98b737a53222
Revises: 3aab366d0549
Create Date: 2024-12-22 13:30:03.022709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b737a53222'
down_revision: Union[str, None] = '3aab366d0549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_question', sa.Column('starter_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_question', 'starter_code')
    # ### end Alembic commands ###
