"""upgrade db

Revision ID: a73e481faa60
Revises: df0fd97cb21b
Create Date: 2025-01-02 14:40:33.936478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73e481faa60'
down_revision: Union[str, None] = 'df0fd97cb21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_main', sa.Column('lecture_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_main', 'lecture_complete')
    # ### end Alembic commands ###
