"""create general tutor parent model

Revision ID: b45f06fda2c9
Revises: 9cfb87646144
Create Date: 2024-11-29 18:57:29.248413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45f06fda2c9'
down_revision: Union[str, None] = '9cfb87646144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_tutor_parent_object',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unique_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_tutor_chat_conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('model_response', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('general_tutor_parent_object_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['general_tutor_parent_object_id'], ['general_tutor_parent_object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_tutor_chat_conversation')
    op.drop_table('general_tutor_parent_object')
    # ### end Alembic commands ###
