"""upgrade db

Revision ID: bcf086119a91
Revises: 4bca7ad3cc32
Create Date: 2024-12-30 13:17:51.065855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf086119a91'
down_revision: Union[str, None] = '4bca7ad3cc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_question', sa.Column('test_function_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_question', 'test_function_name')
    # ### end Alembic commands ###
