"""update database

Revision ID: c75a5cdda4fb
Revises: 7ee77a4e1898
Create Date: 2024-11-13 23:17:19.337851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75a5cdda4fb'
down_revision: Union[str, None] = '7ee77a4e1898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playground_object', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playground_object', 'updated_at')
    # ### end Alembic commands ###
