"""code model

Revision ID: cf28ee1dbfef
Revises: eba585127c5b
Create Date: 2024-12-15 22:03:02.872404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf28ee1dbfef'
down_revision: Union[str, None] = 'eba585127c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('programming_language', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('question_object_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_object_id'], ['user_created_playground_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_code')
    # ### end Alembic commands ###
