"""add tmp problem set question model

Revision ID: dd767085167c
Revises: 423800730f93
Create Date: 2025-01-03 17:19:31.344468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd767085167c'
down_revision: Union[str, None] = '423800730f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_playground_problem_set_chat_conversation', sa.Column('problem_set_object_id', sa.UUID(), nullable=False))
    op.drop_constraint('lecture_playground_problem_set_chat_conversation_p_fkey', 'lecture_playground_problem_set_chat_conversation', type_='foreignkey')
    op.create_foreign_key(None, 'lecture_playground_problem_set_chat_conversation', 'problem_set_question', ['problem_set_object_id'], ['id'])
    op.drop_column('lecture_playground_problem_set_chat_conversation', 'p')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_playground_problem_set_chat_conversation', sa.Column('p', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lecture_playground_problem_set_chat_conversation', type_='foreignkey')
    op.create_foreign_key('lecture_playground_problem_set_chat_conversation_p_fkey', 'lecture_playground_problem_set_chat_conversation', 'problem_set_question', ['p'], ['id'])
    op.drop_column('lecture_playground_problem_set_chat_conversation', 'problem_set_object_id')
    # ### end Alembic commands ###
