"""upgrade db

Revision ID: df0fd97cb21b
Revises: bcf086119a91
Create Date: 2025-01-02 11:30:01.719118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0fd97cb21b'
down_revision: Union[str, None] = 'bcf086119a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_question', sa.Column('function_name', sa.String(), nullable=True))
    op.add_column('lecture_question', sa.Column('class_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_question', 'class_name')
    op.drop_column('lecture_question', 'function_name')
    # ### end Alembic commands ###
