"""pg question

Revision ID: e73d31c01ecd
Revises: 7bad20f1f0b9
Create Date: 2024-12-09 15:26:58.548631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73d31c01ecd'
down_revision: Union[str, None] = '7bad20f1f0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('starter_code', sa.String(), nullable=False),
    sa.Column('solution_code', sa.String(), nullable=False),
    sa.Column('solution_time_complexity', sa.String(), nullable=False),
    sa.Column('example_io_list', sa.String(), nullable=False),
    sa.Column('test_case_list', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground_question')
    # ### end Alembic commands ###
