"""add student course models

Revision ID: ef615f1b5070
Revises: 656bb69ac261
Create Date: 2025-01-14 21:48:19.091775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef615f1b5070'
down_revision: Union[str, None] = '656bb69ac261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_parent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_learned_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_summary_text', sa.String(), nullable=True),
    sa.Column('user_profile_dict', sa.String(), nullable=True),
    sa.Column('user_syllabus_dict', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course_module',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('module_sub_list_string', sa.String(), nullable=True),
    sa.Column('student_course_parent_object_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_course_parent_object_id'], ['student_course_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course_sub_module',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_module_name', sa.String(), nullable=True),
    sa.Column('sub_module_list_string', sa.String(), nullable=True),
    sa.Column('student_course_module_object_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_course_module_object_id'], ['student_course_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course_sub_module')
    op.drop_table('student_course_module')
    op.drop_table('student_learned_profile')
    op.drop_table('student_course_parent')
    # ### end Alembic commands ###
