"""ps implementation object

Revision ID: f9ff8ab6fa7a
Revises: 8913a271f429
Create Date: 2025-01-05 20:39:40.753968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ff8ab6fa7a'
down_revision: Union[str, None] = '8913a271f429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_set_question', sa.Column('implementation_in_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_set_question', 'implementation_in_progress')
    # ### end Alembic commands ###
