"""adding user lecture object

Revision ID: fb9827c3fd84
Revises: f9ff8ab6fa7a
Create Date: 2025-01-06 10:56:50.679054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9827c3fd84'
down_revision: Union[str, None] = 'f9ff8ab6fa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lecture_main',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('custom_user_id', sa.UUID(), nullable=True),
    sa.Column('lecture_main_object_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['custom_user_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['lecture_main_object_id'], ['lecture_main.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lecture_main')
    # ### end Alembic commands ###
